"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";

const cfg:any={profils:["👤","Profils"],communaute:["💬","Communauté"],missions:["💼","Missions"],assistant:["🤖","Assistant IA"],paiements:["💰","Paiements"],challenges:["🏆","Challenges"],formations:["📚","Formations"],afrique:["🌍","Espace Afrique"]};

export default function ModuleClient({module}:{module:string}){
 const [data,setData]=useState<any[]>([]),[user,setUser]=useState<any>(null),[text,setText]=useState(""),[title,setTitle]=useState(""),[settings,setSettings]=useState<any>(null),[price,setPrice]=useState("");
 useEffect(()=>{supabase.auth.getUser().then(r=>setUser(r.data.user));},[]);
 useEffect(()=>{load();supabase.from("platform_settings").select("*").eq("id",true).single().then(r=>setSettings(r.data));},[module,user]);
 async function load(){const t=module==="communaute"?"community_posts":module==="missions"?"missions":module==="challenges"?"challenges":module==="formations"?"courses":module==="afrique"?"africa_posts":module==="paiements"?"payment_requests":"profiles";let q:any=supabase.from(t).select("*").limit(30);if(t==="payment_requests"&&user)q=q.eq("user_id",user.id);const r=await q;setData(r.data||[])}
 async function publish(){if(!user){alert("Connectez-vous d’abord.");return}if(module==="communaute")await supabase.from("community_posts").insert({author_id:user.id,content:text});if(module==="missions")await supabase.from("missions").insert({owner_id:user.id,title,description:text,sale_price:price?Number(price):null,commission_percent:settings?.sale_commission_percent||10,publication_payment_status:"pending"});if(module==="afrique")await supabase.from("africa_posts").insert({author_id:user.id,country:"RDC",content:text});setText("");setTitle("");await load()}
 const c=cfg[module]||cfg.profils;
 return <main className="module-page"><nav><Link href="/"><strong>Developer<span> in DRC</span></strong></Link><Link href="/login">Connexion</Link></nav><section className="module-header"><p>{c[0]} MODULE</p><h1>{c[1]}</h1><p>Votre espace fonctionnel Developer in DRC.</p></section><section className="module-body">{["communaute","missions","afrique"].includes(module)&&<div className="composer">{module==="missions"&&<><input placeholder="Titre de la mission" value={title} onChange={e=>setTitle(e.target.value)}/><input type="number" min="0" step="0.01" placeholder="Prix de vente (USD)" value={price} onChange={e=>setPrice(e.target.value)}/><small>Publication soumise au paiement de {settings?.publication_fee||1} {settings?.publication_currency||"USD"}. Commission sur vente : {settings?.sale_commission_percent||10}%.</small></>}<textarea placeholder="Écrivez ici…" value={text} onChange={e=>setText(e.target.value)}/><button className="primary" onClick={publish}>Publier</button></div>}{module==="assistant"&&<div className="composer"><h2>Assistant IA</h2><textarea placeholder="Votre question technique…"/><button className="primary">Demander à l’IA</button></div>}<div className="grid">{data.map(x=><article key={x.id||x.username}><h3>{x.title||x.full_name||x.username||x.country||"Élément"}</h3><p>{x.description||x.content||x.bio||x.status||x.level||""}</p></article>)}</div></section><footer><Link href="/">← Accueil</Link></footer></main>
}